#!/bin/bash
#
# you have to install the toolchain before you can build curl:
# https://github.com/koreader/koxtoolchain
#

set -eu

openssl_ver='1.1.1d'
curl_ver='7.68.0'

openssl_src='https://www.openssl.org/source'
curl_src='https://curl.haxx.se/download'

PATH=/extern/felix/x-tools/arm-kobo-linux-gnueabihf/bin:$PATH

# install make
sudo apt-get install make

SCRIPT_DIR=$PWD

BUILD_DIR=$(mktemp -d /tmp/build-curl-XXXX)
trap 'rm $BUILD_DIR -rf' EXIT

##
# setup environment
#
export CROSS=arm-kobo-linux-gnueabihf
export CC=${CROSS}-gcc
export LD=${CROSS}-ld
export AS=${CROSS}-as
export AR=${CROSS}-ar

type $CC

set -x

##
# build openssl
#
cd $BUILD_DIR

test -f openssl-${openssl_ver}.tar.gz \
|| wget ${openssl_src}/openssl-${openssl_ver}.tar.gz

tar -xvzf openssl-${openssl_ver}.tar.gz
cd openssl-${openssl_ver}
mkdir -p openssl-install
mkdir -p $BUILD_DIR/openssl-install
./Configure --prefix=$BUILD_DIR/openssl-install linux-armv4 no-heartbeats no-shared
make -j4
make install

##
# build curl
#
cd $BUILD_DIR

test -f curl-${curl_ver}.tar.gz \
|| wget ${curl_src}/curl-${curl_ver}.tar.gz

tar -xvzf curl-${curl_ver}.tar.gz
cd curl-${curl_ver}

# change configure to disable clock_gettime (not available in kobo glibc)
sed -i 's/curl_func_clock_gettime="yes"/curl_func_clock_gettime="no"/g' configure

./configure --host=arm-linux-gnueabi --enable-shared=no --disable-rt \
  --disable-manual --disable-pthreads --disable-threaded-resolver \
  --with-ssl=$BUILD_DIR/openssl-install

# change lib/curl_config.h is changed to disable poll
sed -i 's:\(#define HAVE.*_POLL.*\):/* \1 */:' lib/curl_config.h

make -j4

${CROSS}-strip src/curl
cp src/curl $SCRIPT_DIR/usr/local/kobocloud/
